<?php

namespace hosting\core\libs;
use \Shipard\Utils\Json, \Shipard\Utils\Utils, \Shipard\Base\Utility;


/**
 * class WebProxyCfgCreator
 */
class WebProxyCfgCreator extends Utility
{
  var $serverNdx = 0;

  var $wildCardCerts = [];

  var $cfg = [
    'dsServers' => [],
    'dataSources' => [],
    'webServers' => [],
    'ipv4' => [],
    'certs' => [],
    'cfgFiles' => [],
  ];

  var $forDocumentCard = 0;

  public function setServer($serverNdx)
  {
    $this->serverNdx = $serverNdx;
  }

  protected function loadBaseData()
  {

    $dsServersNdxs = [];
    $dsNdxs = [];

    // -- HW servers
    $q = [];
    array_push($q, 'SELECT servers.*, ');
    array_push($q, ' parentServers.fqdn AS parentFqdn, parentServers.ndx AS parentNdx');
    array_push($q, ' FROM [hosting_core_servers] AS [servers]');
    array_push($q, ' LEFT JOIN [hosting_core_servers] AS [parentServers] ON [servers].[hwServer] = [parentServers].[ndx]');
    array_push($q, ' WHERE 1');
    array_push($q, ' AND ([parentServers].[webProxyServer] = %i)', $this->serverNdx);
    array_push($q, ' AND ([servers].[serverRole] = %i)', 0); // data sources
    $rows = $this->db()->query($q);
    foreach ($rows as $r)
    {
      $dsServerItem = [
        'ndx' => $r['ndx'],
        'fqdn' => $r['fqdn'],
      ];

      $ipv4Addrs = explode(' ', $r['ipv4']);
      if (count($ipv4Addrs))
        $dsServerItem['ipv4'] = $ipv4Addrs[0];

      $this->cfg['dsServers'][$r['ndx']] = $dsServerItem;

      $this->addIPV4Addr($dsServerItem['ipv4'], $r['fqdn']);
    }

    // -- data sources
    $dsNdxs = array_keys($this->cfg['dsServers']);
    if (count($dsNdxs))
    {
      $q = [];
      array_push($q, 'SELECT * FROM [hosting_core_dataSources]');
      array_push($q, ' WHERE 1');
      array_push($q, ' AND [server] IN %in', $dsNdxs);
      $rows = $this->db()->query($q);
      foreach ($rows as $r)
      {
        $srvNdx = $r['server'];
        $srv = $this->cfg['dsServers'][$srvNdx] ?? NULL;
        $this->addDataSource($srv, $r->toArray());
      }
    }
  }

  protected function addDataSource($srv, $dsRecData)
  {
    $addDS = FALSE;
    $dsHostingInfo = NULL;

    $dsHostingInfoRecData = $this->db()->query('SELECT * FROM [hosting_core_dsHostingInfo] WHERE [dataSource] = %i', $dsRecData['ndx'])->fetch();
    if ($dsHostingInfoRecData)
    {
      $dsHostingInfo = Json::decode ($dsHostingInfoRecData['data']);
    }

    $dsItem = [
      'ndx' => $dsRecData['ndx'],
      'dsid' => $dsRecData['gid'],
      'fn' => $dsRecData['name'],
    ];

    if ($dsRecData['dsId1'] !== '')
    {
      $dsItem['appDomain'] = $dsRecData['dsId1'].'.shipard.app';
      $this->addIPV4Addr($srv['ipv4'], $dsItem['appDomain']);
      $addDS = TRUE;
    }

    if ($dsHostingInfo && isset($dsHostingInfo['info']))
    {
      if (isset($dsHostingInfo['info']['webServers']) && count($dsHostingInfo['info']['webServers']))
      {
        foreach ($dsHostingInfo['info']['webServers'] as $ws)
        {
          $wsItem = [
            'ndx' => $ws['ndx'],
            'domain' => $ws['domain'],
            'dsid' => $dsRecData['gid'],
          ];
          $this->addIPV4Addr($srv['ipv4'], $ws['domain']);

          if (isset($ws['redirectHere']) && count($ws['redirectHere']))
          {
            $wsItem['redirectHere'] = $ws['redirectHere'];
            foreach ($ws['redirectHere'] as $rh)
              $this->addIPV4Addr($srv['ipv4'], $rh);
          }

          $this->cfg['webServers'][$ws['ndx']] = $wsItem;
        }
        $addDS = TRUE;
      }
    }

    if ($addDS)
      $this->cfg['dataSources'][$dsRecData['ndx']] = $dsItem;
  }

  protected function addIPV4Addr($addr, $domain)
  {
    if (!isset($this->cfg['ipv4'][$addr]))
      $this->cfg['ipv4'][$addr] = [];

    $this->cfg['ipv4'][$addr][] = $domain;
  }

  protected function createCfgFiles()
  {
    $this->createCfgFiles_etcHosts();
    $this->createCfgFiles_nginx_dsServers();
    $this->createCfgFiles_nginx_dataSources();
    $this->createCfgFiles_nginx_webServers();
  }

  protected function createCfgFiles_etcHosts()
  {
    $cfg = "# >>> /etc/hosts - generated by Shipard Web Proxy server <<<\n";
    $cfg .= "# Do not edit this part, changes will be lost.\n\n";

    foreach ($this->cfg['ipv4'] as $addr => $domains)
    {
      $cfg .= $addr;
      foreach ($domains as $d)
        $cfg .= " ".$d;
      $cfg .= "\n";
    }
    $this->cfg['cfgFiles']['/etc/hosts'] = $cfg;
  }

  protected function createCfgFiles_nginx_dsServers()
  {
    foreach ($this->cfg['dsServers'] as $dsServerNdx => $dsServer)
    {
      $domain = $dsServer['fqdn'];
      $fn = '/etc/nginx/sites-enabled/srv-'.$domain.'-app.conf';
      $cfg = "# data source server ".$domain."\n\n";

      $cfg .= "server {\n";
      $cfg .= "  listen 443 ssl http2;\n";
      $cfg .= "  server_name ".$domain.";\n";

      $cfg .= "  ssl_certificate /etc/ssl/shipard-certs/all.shipard.app/fullchain.pem;\n";
      $cfg .= "  ssl_certificate_key /etc/ssl/shipard-certs/all.shipard.app/privkey.pem;\n";

      $cfg .= "  include /usr/lib/shipard-node/etc/nginx/shn-https.conf;\n";

      $cfg .= "  location / {\n";
      $cfg .= "    proxy_set_header X-Forwarded-For ".'$remote_addr'.";\n";
      $cfg .= "    proxy_pass_request_headers on;\n";
      $cfg .= "    proxy_pass $domain;\n";
      $cfg .= "  }\n";
      $cfg .= "}\n";

      $this->cfg['cfgFiles'][$fn] = $cfg;
    }
  }

  protected function createCfgFiles_nginx_dataSources()
  {
    foreach ($this->cfg['dataSources'] as $dsNdx => $ds)
    {
      $domain = $ds['appDomain'];
      $fn = '/etc/nginx/sites-enabled/ds-'.$ds['dsid'].'_'.$domain.'-app.conf';
      $cfg = "# data source #".$ds['dsid']." / ".$domain."\n\n";

      $cfg .= "server {\n";
      $cfg .= "  listen 443 ssl http2;\n";
      $cfg .= "  server_name ".$domain.";\n";

      $cfg .= "  ssl_certificate /etc/ssl/shipard-certs/all.shipard.app/fullchain.pem;\n";
      $cfg .= "  ssl_certificate_key /etc/ssl/shipard-certs/all.shipard.app/privkey.pem;\n";

      $cfg .= "  include /usr/lib/shipard-node/etc/nginx/shn-https.conf;\n";

      $cfg .= "  location / {\n";
      $cfg .= "    proxy_set_header X-Forwarded-For ".'$remote_addr'.";\n";
      $cfg .= "    proxy_pass_request_headers on;\n";
      $cfg .= "    proxy_pass $domain;\n";
      $cfg .= "  }\n";
      $cfg .= "}\n";

      $this->cfg['cfgFiles'][$fn] = $cfg;
    }
  }

  protected function createCfgFiles_nginx_webServers()
  {
    foreach ($this->cfg['webServers'] as $wsNdx => $ws)
    {
      $domain = $ws['domain'];
      $certId = $this->certId($domain);
      $this->addCert($domain);


      $fn = '/etc/nginx/sites-enabled/ws-'.$domain.'-web.conf';
      $cfg = "# web server #".$ws['dsid']." / ".$domain."\n\n";

      $cfg .= "server {\n";
      $cfg .= "  listen 443 ssl http2;\n";
      $cfg .= "  server_name ".$domain.";\n";

      $cfg .= "  ssl_certificate /etc/ssl/shipard-certs/$certId/fullchain.pem;\n";
      $cfg .= "  ssl_certificate_key /etc/ssl/shipard-certs/$certId/privkey.pem;\n";

      $cfg .= "  include /usr/lib/shipard-node/etc/nginx/shn-https.conf;\n";

      $cfg .= "  location / {\n";
      $cfg .= "    proxy_set_header X-Forwarded-For ".'$remote_addr'.";\n";
      $cfg .= "    proxy_pass_request_headers on;\n";
      $cfg .= "    proxy_pass $domain;\n";
      $cfg .= "  }\n";
      $cfg .= "}\n";

      if (isset($ws['redirectHere']) && count($ws['redirectHere']))
      {
        $cfg .= "\n";
        $cfg .= "server {\n";
        $cfg .= "  listen 443 ssl http2;\n";
        $cfg .= "  server_name ";
        $cfg .= implode(' ', $ws['redirectHere']);
        $cfg .= ";\n";

        $cfg .= "  return 301 https://$domain" . '$request_uri' . ";\n";
        $cfg .= "}\n";
      }

      // -- redirect from http to https
      $cfg .= "\n";
      $cfg .= "server {\n";
      $cfg .= "  listen 80;\n";
      $cfg .= "  server_name ".$domain;
      if (isset($ws['redirectHere']) && count($ws['redirectHere']))
        $cfg .= ' '.implode(' ', $ws['redirectHere']);
      $cfg .= ";\n";
      $cfg .= "  return 301 https://$domain" . '$request_uri' . ";\n";
      $cfg .= "}\n";


      $this->cfg['cfgFiles'][$fn] = $cfg;
    }
  }

  protected function addCert($domain)
  {
    $cid = $this->certId($domain);

    $this->cfg['certs'][$cid] = [
      'domain' => $domain,
      'cid' => $cid,
    ];

    $certData = Utils::loadCfgFile('/var/lib/shipard/hosting/certs/active/'.$cid.'/cert.json');

    $fullChain = $certData['files']['chain.pem'] ?? ' ------------ !!! no cert data !!! ------------ ';
    if ($this->forDocumentCard)
      $fullChain = substr($fullChain, 0, 24).' [censored] '.substr($fullChain, -24);
    $this->cfg['certs'][$cid]['fullchain'] = $fullChain;

    $privKey = $certData['files']['privkey.pem'] ?? ' ------------ !!! no cert data !!! ------------ ';
    if ($this->forDocumentCard)
      $privKey = substr($privKey, 0, 24).' [censored] '.substr($privKey, -24);

    $this->cfg['certs'][$cid]['privkey'] = $privKey;
  }

  protected function certId($domain)
  {
    $parts = explode('.', $domain);
    if (count($parts) > 2)
      $parts = array_slice($parts, -2);

    $baseDomain = implode('.', $parts);

    $cid = $this->wildCardCerts[$baseDomain] ?? $baseDomain;

    return $cid;
  }

  protected function init()
  {
    $q = [];
    array_push($q, 'SELECT * FROM [mac_inet_certs]');
    array_push($q, ' WHERE 1');
    array_push($q, ' AND [host] LIKE %s', '*.%');
    //array_push($q, ' AND [docState] = %i', 4000);

    $rows = $this->db()->query($q);
    foreach ($rows as $r)
    {
      $certDomain = substr($r['host'], 2);
      $certId = $r['fileId'];
      $this->wildCardCerts[$certDomain] = $certId;
    }

    //$this->cfg['wildCardCerts'] = $this->wildCardCerts;

    $this->addCert('shipard.app');
  }

  public function create()
  {
    $this->init();
    $this->loadBaseData();
    $this->createCfgFiles();

    return TRUE;
  }
}
